# Generated by Django 5.2.3 on 2025-06-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do adotante')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Adotante',
                'verbose_name_plural': 'Adotantes',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do animal')),
                ('especie', models.CharField(max_length=50, verbose_name='Espécie')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça')),
                ('idade', models.IntegerField(verbose_name='Idade (em anos)')),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Adotado', 'Adotado')], default='Disponível', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data da doação')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da adoção')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adotante', verbose_name='Adotante')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal adotado')),
            ],
            options={
                'verbose_name': 'Adoção',
                'verbose_name_plural': 'Adoções',
            },
        ),
        migrations.AddField(
            model_name='adotante',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.CreateModel(
            name='Denunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do denunciante')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Denunciante',
                'verbose_name_plural': 'Denunciantes',
            },
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do doador')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doacao', verbose_name='Doação realizada')),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doadores',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da ONG')),
                ('email', models.EmailField(max_length=254, verbose_name='Email da ONG')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco', verbose_name='Endereço da ONG')),
            ],
            options={
                'verbose_name': 'ONG',
                'verbose_name_plural': 'ONGs',
            },
        ),
        migrations.AddField(
            model_name='doacao',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ong', verbose_name='ONG que recebeu'),
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da denúncia')),
                ('data', models.DateField(verbose_name='Data da denúncia')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.denunciante', verbose_name='Denunciante')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ong', verbose_name='ONG responsável')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da campanha')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de término')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ong', verbose_name='ONG responsável')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ong', verbose_name='ONG responsável'),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do veterinário')),
                ('crmv', models.CharField(max_length=20, verbose_name='CRMV')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Veterinário',
                'verbose_name_plural': 'Veterinários',
            },
        ),
        migrations.CreateModel(
            name='SaudeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do atendimento')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veterinario', verbose_name='Veterinário')),
            ],
            options={
                'verbose_name': 'Ficha de Saúde',
                'verbose_name_plural': 'Fichas de Saúde',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do voluntário')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ong', verbose_name='ONG que participa')),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
            },
        ),
    ]
