# Generated by Django 5.2.4 on 2025-07-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saudeanimal',
            options={'verbose_name': 'Saúde Animal', 'verbose_name_plural': 'Saúde Animal'},
        ),
    ]
