# Generated by Django 5.2.3 on 2025-06-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='denunciante',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='doacao',
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doacao',
            options={},
        ),
        migrations.AddField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='nome_denunciante',
            field=models.CharField(default='Anônimo', max_length=100, verbose_name='Nome do denunciante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='forma_pagamento',
            field=models.CharField(default='Outra forma', max_length=50, verbose_name='Forma de pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='nome_doador',
            field=models.CharField(default='Anônimo', max_length=100, verbose_name='Nome do doador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data da denúncia'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data da doação'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='ong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ong', verbose_name='ONG que recebeu'),
        ),
        migrations.DeleteModel(
            name='Denunciante',
        ),
        migrations.DeleteModel(
            name='Doador',
        ),
    ]
