# Generated by Django 5.2.4 on 2025-07-20 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_saudeanimal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='email',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Denunciante'),
        ),
    ]
