# Generated by Django 5.2.3 on 2025-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ocupacao_alter_pessoa_ocupacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saudeanimal',
            options={'verbose_name': 'Saúde Animal', 'verbose_name_plural': 'Saúde Animal'},
        ),
        migrations.RemoveField(
            model_name='saudeanimal',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='saudeanimal',
            name='vacina',
            field=models.CharField(default='Antirrábica', max_length=100, verbose_name='Vacina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saudeanimal',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='saudeanimal',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
