# Generated by Django 5.2.3 on 2025-06-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_denuncia_denunciante_remove_doador_doacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='especie',
            new_name='tipo',
        ),
    ]
