# Generated by Django 5.2.3 on 2025-06-22 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_especie_animal_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='nome_doador',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da doação'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='ong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ong', verbose_name='ONG'),
        ),
    ]
