# Generated by Django 5.2.4 on 2025-07-20 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_denuncia_options_remove_denuncia_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='doacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Doador'),
        ),
    ]
