# Generated by Django 5.2.3 on 2025-06-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_doacao_email_remove_doacao_nome_doador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='nome_doador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do doador'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
