# Generated by Django 5.2.3 on 2025-06-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doacao_email_doacao_nome_doador_doacao_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='ong',
        ),
    ]
