# Generated by Django 5.2.3 on 2025-06-22 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_denuncia_ong'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.endereco', verbose_name='Endereço'),
        ),
    ]
