# Generated by Django 5.2.3 on 2025-06-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_denuncia_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='ong',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='ong',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='ong',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='ong',
        ),
        migrations.DeleteModel(
            name='ONG',
        ),
    ]
